release:
  branches:
    - main
    - release/**
    - lts/**
  plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/npm"
    - - "@semantic-release/git"
      - assets:
          - "package.json"
          - "package-lock.json"
