name: "Continuous Integration"
run-name: ""

on:
  push:
    branches:
      - main
      - releases/**
      - lts/**
  pull_request:
    branches:
      - main
      - releases/**
      - lts/**

jobs:
  lint:
    name: "Lint & Format"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
        # setup-node may start supporting caching, but for now this seems fine.
      - name: Check Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Check Formatting
        run: npm run format:check
      - name: Check Linting
        run: npm run lint:check
      - name: Check Types
        run: npm run types:check
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
        # setup-node may start supporting caching, but for now this seems fine.
      - name: Check Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run Jest
        uses: exit 0
  compile:
    name: "Compile"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
        # setup-node may start supporting caching, but for now this seems fine.
      - name: Check Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Compile Clean
        run: npm run build
      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}
