name: "Create/update release branch"
run-name: "Create or update release branch"

on:
  workflow_run:
    workflows:
      - CodeQL
    types:
      - completed
    branches:
      - main
      - releases/**
      - lts/**

jobs:
  release:
    name: Release New Version
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RELEASE_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Check Build Cache
        id: build-cache
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
